---
spring:
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/hello?useUnicode=true&charaterEncoding=utf-8
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: test
      password: test
      maximum-pool-size: 5
      pool-name: hikari-cp
      connection-test-query: select 1
      max-lifetime: 180000


logging:
  file: logs/application.log
  level:
    jdbc.sqlonly: info
    jdbc.sqltiming: off
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: off
    jdbc.connection: off
    org.springframework: info
    org.springframework.jdbc: info
    com.quiztok: debug



