---
spring:
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://<your-db>:3306/<yours>?useUnicode=true&charaterEncoding=utf-8
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: <your-username>
      password: <your-password>
      maximum-pool-size: 5
      pool-name: hikari-cp
      connection-test-query: select 1
      max-lifetime: 180000


logging:
  file: logs/application.log
  level:
    jdbc.sqlonly: info
    jdbc.sqltiming: info
    jdbc.audit: off
    jdbc.resultset: info
    jdbc.resultsettable: info
    jdbc.connection: off
    org.springframework: info
    org.springframework.jdbc: info
    com.quiztok: debug



